function(function_set_mainCRTStartup argv1 argv2)
    if (MSVC)
        message(${argv1} =======> ${argv2})
        if (${argv2} STREQUAL "win32")
            set_target_properties(${argv1} PROPERTIES WIN32_EXECUTABLE TRUE)
        endif ()
        if (${argv2} STREQUAL "windowsmain")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup")
        elseif (${argv2} STREQUAL "windowswmain")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:WINDOWS /ENTRY:wmainCRTStartup")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:WINDOWS /ENTRY:wmainCRTStartup")
        elseif (${argv2} STREQUAL "windowsnone")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:WINDOWS")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:WINDOWS")
        elseif (${argv2} STREQUAL "consolenone")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_RELEASE "/SUBSYSTEM:CONSOLE")
            set_target_properties(${argv1} PROPERTIES LINK_FLAGS_DEBUG "/SUBSYSTEM:CONSOLE")
        endif ()
    endif ()
endfunction()